"""Public API for the reusable harness and legacy Werewolf adapter.

The package exports contracts eagerly and loads runtime modules lazily so
protocol consumers do not initialize provider SDK clients on import.
"""
from __future__ import annotations

from importlib import import_module
from typing import Any

from .agent_protocol import (
    ActionRequest,
    AgentProtocol,
    DecisionEnvelope,
    LegalAction,
    decision_action_value,
    decision_is_skip,
)
from .core_protocol import (
    ActionChoice as CoreActionChoice,
    ActionOption,
    ActionRequest as CoreActionRequest,
    AgentProtocol as CoreAgentProtocol,
    DecisionEnvelope as CoreDecisionEnvelope,
    SkipChoice as CoreSkipChoice,
    SkipPolicy,
    validate_decision_envelope,
)
from .core_spec import ActorSpec, CoreRunManifest, CoreRunSpec, EnvironmentRef, ExecutionSpec
from .environment import (
    AgentBindingError,
    AgentRegistry,
    EnvironmentDescriptor,
    EnvironmentOutcome,
    EnvironmentRunEvidence,
    EnvironmentRunContext,
    EnvironmentSession,
)
from .registry import EnvironmentRegistry, EnvironmentRegistryError
from .spec import ExperimentSpec, ModelConfigManifest, RunManifest, RunSpec
from .statistics import router_stats_delta
from .transcript import (
    HarnessEvent,
    Transcript,
    TranscriptIntegrityError,
    ValidatedTranscript,
    payload_digest,
    redact_sensitive,
    validated_final_analysis,
    validate_transcript_evidence,
)
from .visibility import VisibilityIssue, audit_transcript_visibility, infer_visibility

_LAZY_EXPORTS: dict[str, tuple[str, str]] = {
    "AgentDecisionError": (".errors", "AgentDecisionError"),
    "ArtifactIntegrityError": (".artifacts", "ArtifactIntegrityError"),
    "VerifiedArtifactSnapshot": (".artifacts", "VerifiedArtifactSnapshot"),
    "DecisionRuntime": (".decision_runtime", "DecisionRuntime"),
    "CoreToolActor": (".core_llm_actor", "CoreToolActor"),
    "CoreCliError": (".core_cli", "CoreCliError"),
    "CoreCliReport": (".core_cli", "CoreCliReport"),
    "DecisionValidationIssue": (".agents", "DecisionValidationIssue"),
    "DecisionValidationResult": (".agents", "DecisionValidationResult"),
    "decision_target_seat": (".agents", "decision_target_seat"),
    "validate_decision_against_legal_actions": (".agents", "validate_decision_against_legal_actions"),
    "load_transcript_jsonl": (".artifacts", "load_transcript_jsonl"),
    "load_verified_artifact_snapshot": (
        ".artifacts",
        "load_verified_artifact_snapshot",
    ),
    "load_verified_run_summary": (".artifacts", "load_verified_run_summary"),
    "verify_run_artifacts": (".artifacts", "verify_run_artifacts"),
    "write_run_artifacts": (".artifacts", "write_run_artifacts"),
    "HarnessBatchResult": (".batch", "HarnessBatchResult"),
    "ExperimentComparativeEvaluation": (".comparison", "ExperimentComparativeEvaluation"),
    "ComparativeExperiment": (".comparison", "ComparativeExperiment"),
    "PairedPolicyComparison": (".comparison", "PairedPolicyComparison"),
    "PairedMetricEstimate": (".comparison", "PairedMetricEstimate"),
    "aggregate_comparative_metrics": (".comparison", "aggregate_comparative_metrics"),
    "DeceptionAggregate": (".deception", "DeceptionAggregate"),
    "DeceptionBeliefShift": (".deception", "DeceptionBeliefShift"),
    "DeceptionSeatMetrics": (".deception", "DeceptionSeatMetrics"),
    "DeceptionSignal": (".deception", "DeceptionSignal"),
    "ExperimentDeceptionEvaluation": (".deception", "ExperimentDeceptionEvaluation"),
    "RunDeceptionAnalysis": (".deception", "RunDeceptionAnalysis"),
    "RunDeceptionMetrics": (".deception", "RunDeceptionMetrics"),
    "aggregate_deception_metrics": (".deception", "aggregate_deception_metrics"),
    "analyze_deception": (".deception", "analyze_deception"),
    "deception_metrics_from_run": (".deception", "deception_metrics_from_run"),
    "EnvironmentRunResult": (".core_runner", "EnvironmentRunResult"),
    "PreparedEnvironmentRun": (".core_runner", "PreparedEnvironmentRun"),
    "ExperimentStrategyEvaluation": (".evaluation", "ExperimentStrategyEvaluation"),
    "ExperimentOperationalEvaluation": (".evaluation", "ExperimentOperationalEvaluation"),
    "OperationalAggregate": (".evaluation", "OperationalAggregate"),
    "RunAuditMetrics": (".evaluation", "RunAuditMetrics"),
    "RunStrategyMetrics": (".evaluation", "RunStrategyMetrics"),
    "RunStrategySeatMetrics": (".evaluation", "RunStrategySeatMetrics"),
    "StrategyAggregate": (".evaluation", "StrategyAggregate"),
    "aggregate_strategy_metrics": (".evaluation", "aggregate_strategy_metrics"),
    "aggregate_operational_metrics": (".evaluation", "aggregate_operational_metrics"),
    "audit_metrics_from_run": (".evaluation", "audit_metrics_from_run"),
    "strategy_metrics_from_run": (".evaluation", "strategy_metrics_from_run"),
    "run_environment_run": (".core_runner", "run_environment_run"),
    "run_core_llm_environment": (".core_llm_runner", "run_core_llm_environment"),
    "run_core_cli": (".core_cli", "run_core_cli"),
    "run_prepared_environment_run": (
        ".core_runner",
        "run_prepared_environment_run",
    ),
    "run_experiment_spec": (".batch", "run_experiment_spec"),
    "run_experiment_spec_sync": (".batch", "run_experiment_spec_sync"),
    "RunSummaryRow": (".results", "RunSummaryRow"),
    "run_summary_from_result": (".results", "run_summary_from_result"),
    "HarnessRunResult": (".runner", "HarnessRunResult"),
    "run_werewolf_run": (".runner", "run_werewolf_run"),
    "run_werewolf_run_sync": (".runner", "run_werewolf_run_sync"),
    "resolve_run_spec": (".runner", "resolve_run_spec"),
    "RunSpecLoadError": (".spec_loader", "RunSpecLoadError"),
    "legacy_werewolf_run_to_core": (".spec_loader", "legacy_werewolf_run_to_core"),
    "load_core_run_spec": (".spec_loader", "load_core_run_spec"),
    "build_policy_schedule": (".schedule", "build_policy_schedule"),
    "apply_seat_permutation": (".schedule", "apply_seat_permutation"),
    "apply_seat_mapping_permutation": (".schedule", "apply_seat_mapping_permutation"),
    "default_experiment_id": (".schedule", "default_experiment_id"),
    "experiment_metadata": (".schedule", "experiment_metadata"),
    "ExperimentSummary": (".summary", "ExperimentSummary"),
    "summarize_runs": (".summary", "summarize_runs"),
    "RealModelSmokeReport": (".smoke", "RealModelSmokeReport"),
    "RealModelSmokeVerificationError": (".smoke", "RealModelSmokeVerificationError"),
    "verify_real_model_smoke_artifacts": (".smoke", "verify_real_model_smoke_artifacts"),
    "ExpectedInvariant": (".scenarios", "ExpectedInvariant"),
    "InvariantResult": (".scenarios", "InvariantResult"),
    "ScenarioReport": (".scenarios", "ScenarioReport"),
    "ScenarioSpec": (".scenarios", "ScenarioSpec"),
    "ScenarioSuiteReport": (".scenarios", "ScenarioSuiteReport"),
    "run_adversarial_scenario": (".scenarios", "run_adversarial_scenario"),
    "run_adversarial_scenario_suite": (
        ".scenarios",
        "run_adversarial_scenario_suite",
    ),
}

__all__ = [
    "ActionRequest",
    "ActionOption",
    "AgentDecisionError",
    "AgentBindingError",
    "AgentProtocol",
    "AgentRegistry",
    "ActorSpec",
    "ArtifactIntegrityError",
    "CoreActionChoice",
    "CoreActionRequest",
    "CoreAgentProtocol",
    "CoreCliError",
    "CoreCliReport",
    "CoreDecisionEnvelope",
    "CoreRunManifest",
    "CoreRunSpec",
    "CoreSkipChoice",
    "CoreToolActor",
    "DecisionEnvelope",
    "DecisionValidationIssue",
    "DecisionValidationResult",
    "DecisionRuntime",
    "DeceptionAggregate",
    "DeceptionBeliefShift",
    "DeceptionSeatMetrics",
    "DeceptionSignal",
    "EnvironmentDescriptor",
    "EnvironmentOutcome",
    "EnvironmentRef",
    "EnvironmentRegistry",
    "EnvironmentRegistryError",
    "EnvironmentRunEvidence",
    "EnvironmentRunContext",
    "EnvironmentRunResult",
    "EnvironmentSession",
    "ExperimentStrategyEvaluation",
    "ExperimentOperationalEvaluation",
    "ExperimentDeceptionEvaluation",
    "ExperimentComparativeEvaluation",
    "ComparativeExperiment",
    "PairedPolicyComparison",
    "PairedMetricEstimate",
    "PreparedEnvironmentRun",
    "ExecutionSpec",
    "ExpectedInvariant",
    "ExperimentSpec",
    "ExperimentSummary",
    "HarnessBatchResult",
    "HarnessEvent",
    "HarnessRunResult",
    "InvariantResult",
    "LegalAction",
    "ModelConfigManifest",
    "OperationalAggregate",
    "RunManifest",
    "RunDeceptionAnalysis",
    "RunDeceptionMetrics",
    "RunAuditMetrics",
    "RealModelSmokeReport",
    "RealModelSmokeVerificationError",
    "RunSpec",
    "RunStrategyMetrics",
    "RunStrategySeatMetrics",
    "RunSpecLoadError",
    "RunSummaryRow",
    "ScenarioReport",
    "ScenarioSpec",
    "ScenarioSuiteReport",
    "SkipPolicy",
    "StrategyAggregate",
    "Transcript",
    "TranscriptIntegrityError",
    "ValidatedTranscript",
    "VerifiedArtifactSnapshot",
    "VisibilityIssue",
    "audit_transcript_visibility",
    "apply_seat_permutation",
    "apply_seat_mapping_permutation",
    "build_policy_schedule",
    "decision_action_value",
    "decision_is_skip",
    "decision_target_seat",
    "default_experiment_id",
    "experiment_metadata",
    "infer_visibility",
    "legacy_werewolf_run_to_core",
    "load_core_run_spec",
    "load_transcript_jsonl",
    "load_verified_artifact_snapshot",
    "load_verified_run_summary",
    "payload_digest",
    "redact_sensitive",
    "resolve_run_spec",
    "router_stats_delta",
    "run_adversarial_scenario",
    "run_adversarial_scenario_suite",
    "run_experiment_spec",
    "run_experiment_spec_sync",
    "run_environment_run",
    "run_core_cli",
    "run_core_llm_environment",
    "run_prepared_environment_run",
    "run_summary_from_result",
    "run_werewolf_run",
    "run_werewolf_run_sync",
    "summarize_runs",
    "aggregate_deception_metrics",
    "aggregate_comparative_metrics",
    "aggregate_strategy_metrics",
    "aggregate_operational_metrics",
    "audit_metrics_from_run",
    "strategy_metrics_from_run",
    "analyze_deception",
    "deception_metrics_from_run",
    "validate_decision_against_legal_actions",
    "validate_decision_envelope",
    "validate_transcript_evidence",
    "validated_final_analysis",
    "verify_run_artifacts",
    "verify_real_model_smoke_artifacts",
    "write_run_artifacts",
]


def __getattr__(name: str) -> Any:
    target = _LAZY_EXPORTS.get(name)
    if target is None:
        raise AttributeError(f"module {__name__!r} has no attribute {name!r}")
    module_name, attribute = target
    value = getattr(import_module(module_name, __name__), attribute)
    globals()[name] = value
    return value
